# Theme Check Configuration
# https://shopify.dev/docs/themes/tools/theme-check/configuration

# Ignore missing app blocks - these are third-party apps installed in production
# but not available in local development environment
JSONMissingBlock:
  enabled: true
  # Ignore app blocks that are only available in production
  ignore:
    - templates/index.json
    - templates/product.json

# Ignore translation key error - key exists but theme check may be caching
TranslationKeyExists:
  enabled: true
  ignore:
    - sections/header-marquee.liquid
